<a href="https://colab.research.google.com/github/Sowmya06-student/Data-Analytics-using-Python-Project/blob/main/day_3_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
try:
  num=int(input("enter:"))
  print(num)
except:
  print("Invalid input")

enter:abc
Invalid input


In [ ]:
import numpy as np
marks=np.array([90,85,78,92])
print(marks)

[90 85 78 92]


In [ ]:
import numpy as np
students=np.array([
    [90,85],
    [78,92],
    [88,45],
])
print(students)

[[90 85]
 [78 92]
 [88 45]]


In [ ]:
import numpy as np
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np
marks=np.array([98,85,78,92])
print(marks[2])

78


In [ ]:
import numpy as np
marks=np.array([98,85,78,63,87,94])
print(marks[1:4])

[85 78 63]
